name: easy_pay_bank_infomrm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4+6

environment:
  sdk: ^3.9.2

dependencies:
  bot_toast: ^4.1.3
  device_info_plus: ^12.3.0
  dio: ^5.9.2
  easy_localization: ^3.0.8
  # file_picker: ^10.3.10
  flutter:
    sdk: flutter

  # Yenyi Fork
  pull_to_refresh:
    git:
      url: https://github.com/yenyichau/flutter_pulltorefresh.git

      
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^2.9.1+2
  lottie: ^3.3.2
  material_design_icons_flutter: ^7.0.7296
  mime: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  open_settings_plus: ^0.4.2
  package_info_plus: ^9.0.0
  page_transition: ^2.2.1
  permission_handler: ^12.0.1
  pinput: ^6.0.2
  platform_info: ^5.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  names_launcher: ^0.0.2
  flutter_launcher_icons: ^0.14.4
  ntp: ^2.0.0
  calendar_date_picker2: ^2.0.1
  omni_datetime_picker: ^2.3.1
  flutter_local_notifications: ^21.0.0
  awesome_notifications: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  # image_path: "assets/icon/logo.png" # 這是你圖片的路徑
  image_path: "assets/easy_pay/logo.png" # 這是你圖片的路徑
  # image_path: "assets/three_sixty/logo.png" # 這是你圖片的路徑
  min_sdk_android: 21 # 可選，設定 Android 最低版本支援
  remove_alpha_ios: true # 強烈建議加上：自動移除 iOS 圖標的透明度，避免審核被拒

names_launcher:
  name: "代付辅助系统"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/lotties/
    - assets/easy_pay/
    - assets/three_sixty/
    - assets/icon/



    # flutter build apk --flavor easyPay -t lib/main_easy_pay.dart
    # flutter build apk --flavor threeSixty -t lib/main_360.dart
    # flutter pub run flutter_launcher_icons     
